name: preseis_model_building
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - rioxarray
  - xarray
  - h5netcdf
  - h5py
  - pyproj
  - ca-certificates
  - openssl
  - pytest
  - wget
  - certifi
  - python-wget
  - tqdm
  - ipykernel
  - json5
  - pip
  - matplotlib
  - contextily
  - pytest
  - pytest-cov
  - pip:
    - zmapio
